services:
  app1:
    image: heartocean/docom:spring1
    ports:
      - 8080:8080
    environment: 
      - MONGO_DB_HOSTNAME=mongo1
      - MONGO_DB_USERNAME=prod
      - MONGO_DB_PASSWORD=prod@123
    networks:
      - app1network

  mongo1:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prod
      - MONGO_INITDB_ROOT_PASSWORD=prod@123
    networks:
      - app1network
    volumes:
      - vol1:/data/db

volumes:
  vol1:

networks:
  app1network:
